#!/bin/bash

export RESM='/usr/lib/resm'

start() {
	cd $RESM && screen -S resm -d -m python3 resm.py
}

stop() {
	screen -X -S resm quit
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    *)
       echo "Usage: $0 {start|stop|restart}"
esac

exit 0 
